sudo: required

services:
  - docker

before_install:
  - docker build -t provisionary:latest .
  - docker run -d -p 80:80 provisionary:latest

script:
  - curl -s -o /dev/null -w "%{http_code}" http://drupal7.dev
  - test "200" -eq $(curl -s -o /dev/null -w "%{http_code}" http://drupal7.dev)

addons:
  hosts:
    - drupal7.dev
