sudo: required

services:
  - docker

before_install:
  - docker build -t provisionary:latest .
  - id=$(docker run -d -p 8000:80 provisionary:latest)
  - docker logs $id

script:
  - cat /etc/hosts
  - curl -v -I http://localhost:8000
  - curl -v -I http://drupal7.dev:8000
  - test "200" -eq $(curl -s -o /dev/null -w "%{http_code}" http://drupal7.dev:8000)

addons:
  hosts:
    - drupal7.dev
